version: "2.1"
services:
  faketimentpcombo:
    build: .
    image: cturrabased/ntp:latest
    container_name: ntp-fake
    restart: always
    ports:
      - 123:123/udp
    environment:
      - NTP_SERVERS="127.127.127.1"